// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://apetvnjnrswyvtyqctlj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwZXR2bmpucnN3eXZ0eXFjdGxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0ODg5OTcsImV4cCI6MjA5MTA2NDk5N30.nTcOd5_0Fj4lEq4uYyRZ9-62slHWDfOr3lB9UPwAXzk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);